export const GESTURE_TYPES = Object.freeze({
    SALE_CHECKOUT: 'SALE_CHECKOUT',
    SALE_EXCHANGE: 'SALE_EXCHANGE',
    RENTAL_BOOK: 'RENTAL_BOOK',
    RENTAL_HANDOVER: 'RENTAL_HANDOVER',
    RENTAL_AMEND: 'RENTAL_AMEND',
    RENTAL_CANCEL: 'RENTAL_CANCEL',
    RENTAL_SETTLE: 'RENTAL_SETTLE',
    RENTAL_WRITE_OFF: 'RENTAL_WRITE_OFF',
    UNIT_RECOVER: 'UNIT_RECOVER',
    UNIT_TRANSITION: 'UNIT_TRANSITION',
    EXPENSE_CREATE: 'EXPENSE_CREATE',
    EXPENSE_REVERSE: 'EXPENSE_REVERSE',
    INTAKE_SCAN: 'INTAKE_SCAN',
    BARCODE_GENERATE: 'BARCODE_GENERATE',
    BARCODE_GENERATE_TEST: 'BARCODE_GENERATE_TEST',
});

export const GESTURE_TYPES_ARRAY = Object.freeze(Object.values(GESTURE_TYPES));
